# Model
transformer: huggingface
transformer_conf:
    hf_model_tag: HuggingFaceTB/SmolLM-360M
    
corelm: ar_multiscale
corelm_conf:
    share_emb: false
    qk_norm: true
    l_att_unit: 512
    l_head: 8
    l_layer: 6

# loss
modality_weights: {
    "g2p": 1.0,
    "ssl": 0.5,
    "codec": 0.0625,
    "text_bpe": 1.0,
    "special_token": 10.0,
}
loss_region: whole

# General Dataloader configuration
batch_type: numel
batch_bins: 12000
num_iters_per_epoch: 10000
max_epoch: 60
num_workers: 6
drop_last_iter: true
log_interval: 1000

# optimization
optim: adamw
grad_clip: 5
accum_grad: 1
use_amp: true
num_att_plot: 0
optim_conf:
    lr: 0.001
    betas:
        - 0.9
        - 0.95
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

best_model_criterion:
-   - valid
    - total_count
    - max

# Data preprocessing
codec_token_per_frame: 9
codec_token_in_use: 9
speaker_prompt_length: 500

# specaug
asr_apply_time_mask: true
asr_time_mask_config:
    mask_width_ratio_range:
    - 0.
    - 0.05
    num_mask: 10
